#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# chisel documentation build configuration file, created by
# sphinx-quickstart on Tue Jul 21 06:35:47 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# Import the chisel module.
sys.path.insert(0, os.path.abspath('..'))
import chisel

# Autodoc.
extensions = [ "sphinx.ext.autodoc" ]
autodoc_member_order = 'bysource'

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'chisel'
copyright = '2012-2015, Craig Hobbs'
author = 'Craig Hobbs'

# The short X.Y version.
version = chisel.__version__
# The full version, including alpha/beta/rc tags.
release = chisel.__version__

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'classic'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []
