# Licensed under the MIT License
# https://github.com/craigahobbs/chisel/blob/master/LICENSE

include Makefile.base

$(eval $(call COMPILE_CHSL, markdownTypes))
$(eval $(call COMPILE_CHSL, typeModel))
