# Licensed under the MIT License
# https://github.com/craigahobbs/chisel/blob/master/LICENSE

include Makefile.base

$(eval $(call COMPILE_SMD, typeModel))
$(eval $(call COMPILE_SMD, markdownModel, Markdown Model))
